language: node_js # node环境
sudo: required
node_js:
  - lts/*
branch: main
branches:
  only:
    - main
cache:
  directories:
    - node_modules
before_install:
  - export TZ='Asia/Shanghai'
  - chmod +x deploy.sh
script:
  - deploy.sh
