language: node_js # node环境
sudo: required
node_js:
  - lts/*
cache:
  directories:
    - node_modules
branches:
  only:
    - main
script:
  - echo "skipping tests"
deploy:
  provider: pages
  skip_cleanup: true
  script: chmod +x ./deploy.sh && ./deploy.sh
  on:
    branch: main
